### ISSUE TITLE
use a server module

### ISSUE THREAD

**Issue by falood** [elixir-maru/maru#106]
something like Ecto and other apps, use a standalone module to run server, mount server to it's own supervisor tree.

```
defmodule MyServer do
  # config :my_api, MyServer,
  #   adapter: Cowboy2,
  #   plug: MyAPI,
  #   port: 8080,
  #   scheme: :http,
  #   bind_addrsss: 0.0.0.0
  use Maru.Server, otp_app: :my_api

  def init(_type, _opts) do
    {
      :ok,
      [
        adapter: Cowboy2,
        plug: MyAPI,
        port: 8080,
        scheme: :http,
        bind_addrsss: 0.0.0.0
      ]
    }
  end
end


defmodule MyAPI do
  use MyServer

  ...
end
```
and then add `worker(MyServer, [])` to supervisor tree.

**Comment by jalcine** [comment]
What are the advantages/disadvantages of doing this?

Allowing for composite servers could allow developers to scale individual workers for servers a lot more efficient (when leveraging the supervisor/worker model).

**Comment by falood** [comment]
## Advantages
> I use maru on my own production, we have 4 http servers run on the same node, most advantages are for this use case.
 
1. different servers can be started by different application. For now, we start all servers by `Application.start :maru`, it can't resolve depends issue, we may need to start by custom order.
2. It decouple different servers, for example we can let `Maru.Type` bind to service, then we don't need to define `Maru.Type.UserID` for all services, we may need to define `MyService.Types.UserID` and `import_type MyServices.Types` in the server module.
3. it's also designed for `plugin`, we may use different plugin in different services.
4. there's `root_plug` in current version, it's a bad design, I think everything belongs to `root_plug` can be moved to server module.

No Disadvantages, I think everything is better.

**Comment by jalcine** [comment]
Okay. I took some time to think over this. This would make Maru more portable and flexible to process control. I'm down for this.

What are some roadblocks that are visible right now? Outside of tests and sample code to make sure it works, that is.

**Comment by falood** [comment]
Nothing, I'm still thinging about how to migrate smooth.
