### ISSUE TITLE
Followed the guide but server curl test does not work

### ISSUE THREAD

**Issue by andrewvmail** [elixir-maru/maru#120]
Just starting out with elixir and maru but cant get cowboy up for some reason. I carefully followed the guide in the readme. The example repo with the old deps works though ... any ideas?

Cheers

```
git clone https://github.com/andrewvmail/my_app
cd my_app
mix deps.get
iex -S mix   
```

**Comment by falood** [comment]
I'm sorry @andrewvmail , I have too many email in my inbox and I missed the previous message.

**Comment by andrewvmail** [comment]
No worries, but yeah for some reason i couldn't get it to work. Take your time I'm just playing around with vanilla Elixir at the moment.

**Comment by falood** [comment]
this patch will fix the issue 🙂
```
diff --git a/mix.exs b/mix.exs
index 7676702..597a38b 100644
--- a/mix.exs
+++ b/mix.exs
@@ -14,6 +14,7 @@ defmodule MyApp.MixProject do
   # Run "mix help compile.app" to learn about applications.
   def application do
     [
+      mod: {MyApp.Application, []},
       extra_applications: [:logger]
     ]
   end
```

**Comment by andrewvmail** [comment]
Thanks!
