### ISSUE TITLE
several rescue_from?

### ISSUE THREAD

**Issue by sdesbure** [elixir-maru/maru#40]
Hello, I've got a definition like this:

``` ruby
defmodule MyApp.API do
  use Maru.Router
  mount MyApp.API.Test
 get do
    conn |> text("It works!")
  end

  rescue_from :all, as: e do
    conn
    |> put_status(500)
    |> text("ERROR: #{inspect e}")
  end
end
```

and in `MyApp.API.Test`:

``` ruby
defmodule MyApp.API.Test do
  use Maru.Router
  plug Plug.Logger

  namespace :test do
    params do
      requires :Product_ID, type: String
    end 

    get do
      json(conn, %{"Result" => "yes"}
    end

    rescue_from [ Maru.Exceptions.Validation, Maru.Exceptions.InvalidFormatter ] do
    conn                                                                                                   
      |> put_status(500)
      |> json(%{"error" => %{"code" => 0, 
                      "context" => "context", 
                      "message" => "this is an error"})
    end
  end
end 
```

As you see, I have 2 `rescue_from` and the inner one doesn't work. Regarding the implementation, it's seems to be OK.
But if I remove the outer (`rescue_from :all`), the inner still doesn't work :(
And if I put the inner in `MyApp.API` then my tests are failing (the error is not catched).
Any idea how to do that?

I'm mimicking an already deployed app server so I don't really have the choice for the error handling output...

**Comment by falood** [comment]
Hi @sdesbure , this is a known issue.
I have had too many personal things to do for almost a month, and I'll start hacking this weekend and fix this soon!

**Comment by falood** [comment]
Hi @sdesbure ,
I just pushed a commit to master for several rescue_from support, you can check these [unittest](https://github.com/falood/maru/blob/44311857ea7b0050a5b16242dcffad2129a6ebe7/test/builder/exceptions_test.exs#L129-L183) to understand the general.
But, `rescue_from` is bind to router, not endpoint. So you should keep it out of `namespace` `resources` and so on.
If you have any question, leave me a message please.

**Comment by falood** [comment]
Could I close this issue now?

**Comment by sdesbure** [comment]
Hello, I'm deeply sorry, I forgot to close. It works! Thank you
