### ISSUE TITLE
Maru might not allow for dynamic configuration

### ISSUE THREAD

**Issue by samvv** [elixir-maru/maru#52]
Don't shoot me if I'm wrong, but I _think_ this is an issue with Maru. The context is rather simple: I modified the configuration using `Application.put_env` before starting my dependencies such as Maru, but for some reason Maru does not respect this new configuration, even though when I use `Application.get_env` it reports the new configuration just as you would expect.

I would love to fix it myself, but unfortunately I have no clue about what is going on, because [the soruce](https://github.com/elixir-maru/maru/blob/7a24d1a30f95fba5abb6edd974ecd27a7e117620/lib/maru.ex#L43) suggests Maru does load the configuration after it is started. Is there any chance you could look into it or tell me that it doesn't have anything to do with Maru? That would be really great. For more information, see samvv/elixir-takeoff#1.

**Comment by samvv** [comment]
Whoops, turned out it was a simple mistake. I forgot to add the `:persistent` flag. Never mind me. ;)

**Comment by falood** [comment]
I'm sorry I haven't get your point but it seems you have found your answer 🙂 
feel free to leave me a message if anything I can help
