### ISSUE TITLE
Top Middleware not executing during tests

### ISSUE THREAD

**Issue by jmnsf** [elixir-maru/maru#62]
Plugs mounted in a parent router aren't being run on the child routers during tests. I could work up a test case but there's one in the docs: the second code sample in [this page](https://maru.readme.io/docs/testing) doesn't pass.

```
  1) test / (API.MountedTest)
     test/random_mix_test.exs:28
     ** (KeyError) key :maru_plug_test not found in: %{maru_params: %{}, maru_test: true, maru_version: nil}
     stacktrace:
       test/random_mix_test.exs:30: (test)
```

**Comment by falood** [comment]
Hi @jmnsf 
I built many "magic" in unittest of maru, but it seems not easy to use, so I have to revert them.
The latest modifies are in master brunch, I'll bump a new version soon. before the new release, I help to fix unittest of your project legacy with master version, could you please take a look whether it's good for you?
Thanks.

**Comment by jmnsf** [comment]
It's working great, thank you @falood :)

**Comment by falood** [comment]
@jmnsf can you also help to check https://github.com/elixir-maru/maru/issues/55 ? Thanks
