### ISSUE TITLE
Unnamed parameter lists

### ISSUE THREAD

**Issue by acerberus** [elixir-maru/maru#65]
Hi,

I was wondering if it is possible to define an unnamed parameter list. Something in the following style:

```
params do
	requires  type: List do
	  requires :foo, type: String
	  requires :bar, type: String
	end
  end
```

The idea is to send json arrays, for example;

`[ {"foo" : "foobar", "bar": "foobar"}, ...]`

As far as I can tell, all parameters have to be named, which usually makes sense, except for the above use case. Any help or pointers are much appreciated.

**Comment by falood** [comment]
Hi @acerberus 
Plug doesn't handle list parameter.
With `curl -XPOST 127.0.0.1:8828/list_test -H 'Content-Type: application/json'  -d '[1, 2, 3]'` , I get `%{"_json" => [1, 2, 3]}` when run `conn.params`, so the name of `unnamed parameter lists` is `_json`, you can handle it with such code: 

```elixir
params do
  requires :_json, type: List do
end
```

**Comment by acerberus** [comment]
Hi @falood, 
works like a charm. Thanks for the quick response and the good work on maru.
