### ISSUE TITLE
could not compile dependency :maru

### ISSUE THREAD

**Issue by Mo33n** [elixir-maru/maru#71]
run this command after deps.get : mix deps.compile maru
==> maru
Compiling 59 files (.ex)

== Compilation error in file lib/maru/plugs/version.ex ==
** (CompileError) lib/maru/plugs/version.ex:32: expected -> clauses for :else in "with"

could not compile dependency :maru, "mix compile" failed. You can recompile this dependency with "mix deps.compile maru", update it with "mix deps.update maru" or clean it with "mix deps.clean maru"

**Comment by falood** [comment]
Hi @Mo33n 
could you please tell me what version of elixir and erlang are you using with maru?

**Comment by Mo33n** [comment]
I just downgraded the erlang from 20 to 19.3 and problem is solved. 

thanks

**Comment by falood** [comment]
erlang 1.3.x doesn't work well with erlang 20, maru tested under these verions of erlang and elixir: 
https://github.com/elixir-maru/maru/blob/master/.travis.yml
