### ISSUE TITLE
Jason is optional dependency

### ISSUE THREAD

**Issue by arkgil** [elixir-maru/maru#97]
Hi!

I've noticed that in dependencies list `Jason` is marked as optional:
https://github.com/elixir-maru/maru/blob/595e30736ea6f3e1fea2d9ef19cda8e5fa8912cc/mix.exs#L32

However, `Jason` is a default when fetching JSON library from application environment:
https://github.com/elixir-maru/maru/blob/595e30736ea6f3e1fea2d9ef19cda8e5fa8912cc/lib/maru.ex#L62

If someone forgets to configure JSON library specifically, or doesn't add `Jason` to deps, undefined function errors show up because the module is not there.

I'd happily prepare a PR if that is something you're willing to accept 🙂

**Comment by falood** [comment]
Hi @arkgil ,

It seems it's a general way to do like this in elixir world, as far as I know, phoenix and ecto also do it like this.

https://github.com/elixir-ecto/ecto/blob/master/mix.exs#L54
https://github.com/phoenixframework/phoenix/blob/master/mix.exs#L60

**Comment by arkgil** [comment]
Yes, I'm aware that marking dependency as optional is a common practice. However, it's a little bit different in case of the two projects you've mentioned:
* Phoenix configures JSON library for you when you generate a new project
* Most of Ecto's functionality doesn't require JSON library

I'd say that Maru is mostly used for building JSON APIs (although I might be completely wrong here), so JSON library is essential in this kind of project. It would be nice if Maru would raise an explicit error if no such library is present 💥 

Another, simpler solution is to just point out in the documentation that JSON library needs to be added to deps explicitly to be able to build a JSON API 📝  What do you think, @falood? 🙂

**Comment by arkgil** [comment]
@falood Thanks! I've left one comment in the PR 😄
