### ISSUE TITLE
could not find application file: ranch.app

### ISSUE THREAD

**Issue by rafaelvicio** [elixir-maru/maru#99]
I'm doing the basic example of the documentation, and I'm getting the following error

> iex -S mix
> Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
> 
> ** (Mix) Could not start application ranch: could not find application file: ranch.app

my project: https://github.com/rafaelvicio/elixirrest

elixir -v
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.4 (compiled with OTP 19)

**Comment by falood** [comment]
https://github.com/rafaelvicio/elixirrest/pull/1
just made this pr to init the project
